"""empty message

Revision ID: aade8d0a3974
Revises: 2.1
Create Date: 2021-12-29 10:52:50.028611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2.2"
down_revision = "2.1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account", sa.VARCHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.Column("email", sa.VARCHAR(), nullable=True),
        sa.Column("user_role", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("agencys", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_agencys_user_id", "user", ["user_id"], ["id"])

    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_customers_user_id", "user", ["user_id"], ["id"])

    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_expenses_user_id", "user", ["user_id"], ["id"])

    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_invoices_user_id", "user", ["user_id"], ["id"])
        batch_op.drop_column("items_id")

    with op.batch_alter_table("invoices_item", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_invoices_item_user_id", "user", ["user_id"], ["id"]
        )

    with op.batch_alter_table("jobtypes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_jobtypes_user_id", "user", ["user_id"], ["id"])

    with op.batch_alter_table("paymentdetails", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_paymentdetails_user_id", "user", ["user_id"], ["id"]
        )

    with op.batch_alter_table("personaldetails", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_personaldetails_user_id", "user", ["user_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("personaldetails", schema=None) as batch_op:
        batch_op.drop_constraint("fk_personaldetails_user_id", type_="foreignkey")
        batch_op.drop_column("user_id")

    with op.batch_alter_table("paymentdetails", schema=None) as batch_op:
        batch_op.drop_constraint("fk_paymentdetails_user_id", type_="foreignkey")
        batch_op.drop_column("user_id")

    with op.batch_alter_table("jobtypes", schema=None) as batch_op:
        batch_op.drop_constraint("fk_jobtypes_user_id", type_="foreignkey")
        batch_op.drop_column("user_id")

    with op.batch_alter_table("invoices_item", schema=None) as batch_op:
        batch_op.drop_constraint("fk_invoices_item_user_id", type_="foreignkey")
        batch_op.drop_column("user_id")

    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.add_column(sa.Column("items_id", sa.INTEGER(), nullable=True))
        batch_op.drop_constraint("fk_invoices_user_id", type_="foreignkey")
        batch_op.drop_column("user_id")

    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.drop_constraint("fk_expenses_user_id", type_="foreignkey")
        batch_op.drop_column("user_id")

    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.drop_constraint("fk_customers_user_id", type_="foreignkey")
        batch_op.drop_column("user_id")

    with op.batch_alter_table("agencys", schema=None) as batch_op:
        batch_op.drop_constraint("fk_agencys_user_id", type_="foreignkey")
        batch_op.drop_column("user_id")

    op.drop_table("user")
    # ### end Alembic commands ###
