"""empty message

Revision ID: c27b38186403
Revises: 1.1
Create Date: 2021-12-25 11:46:28.208496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2.0"
down_revision = "1.1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("_alembic_tmp_expenses")
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.create_unique_constraint("uc_expenses_id", ["expense_id"])

    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.create_unique_constraint("uc_invoices_id", ["invoice_id"])

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.add_column(sa.Column("items_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "invoices_item", ["items_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.drop_constraint("uc_invoices_id", type_="unique")

    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.drop_constraint("uc_expenses_id", type_="unique")

    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("items_id")
    # ### end Alembic commands ###
