"""empty message

Revision ID: f9dbf224121c
Revises: 80132f8ad23d
Create Date: 2021-04-23 12:06:58.943777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1.0"
down_revision = "0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agencys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.Column("percentage", sa.FLOAT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_engine="InnoDB",
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.Column("email", sa.VARCHAR(), nullable=True),
        sa.Column("phone", sa.VARCHAR(), nullable=True),
        sa.Column("contact", sa.VARCHAR(), nullable=True),
        sa.Column("street", sa.VARCHAR(), nullable=True),
        sa.Column("postcode", sa.Integer(), nullable=True),
        sa.Column("city", sa.VARCHAR(), nullable=True),
        sa.Column("country", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_engine="InnoDB",
    )
    op.create_table(
        "expenses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("expense_id", sa.VARCHAR(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("cost", sa.FLOAT(), nullable=True),
        sa.Column("comment", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_engine="InnoDB",
    )
    op.create_table(
        "jobtypes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_engine="InnoDB",
    )
    op.create_table(
        "paymentdetails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.VARCHAR(), nullable=True),
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.Column("bank", sa.VARCHAR(), nullable=True),
        sa.Column("IBAN", sa.VARCHAR(), nullable=True),
        sa.Column("BIC", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_engine="InnoDB",
    )
    op.create_table(
        "personaldetails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.VARCHAR(), nullable=True),
        sa.Column("name_company", sa.VARCHAR(), nullable=True),
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.Column("street", sa.VARCHAR(), nullable=True),
        sa.Column("postcode", sa.Integer(), nullable=True),
        sa.Column("city", sa.VARCHAR(), nullable=True),
        sa.Column("mail", sa.VARCHAR(), nullable=True),
        sa.Column("phone", sa.VARCHAR(), nullable=True),
        sa.Column("taxnumber", sa.VARCHAR(), nullable=True),
        sa.Column("payment_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["paymentdetails.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_engine="InnoDB",
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.VARCHAR(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("description", sa.VARCHAR(), nullable=True),
        sa.Column("invoice_ammount", sa.FLOAT(), nullable=True),
        sa.Column("invoice_mwst", sa.FLOAT(), nullable=True),
        sa.Column("paydate", sa.Date(), nullable=True),
        sa.Column("invoice_data", sa.JSON(), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("jobcode_id", sa.Integer(), nullable=True),
        sa.Column("agency_id", sa.Integer(), nullable=True),
        sa.Column("personal_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["agencys.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["jobcode_id"],
            ["jobtypes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["personal_id"],
            ["personaldetails.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("invoices")
    op.drop_table("personaldetails")
    op.drop_table("paymentdetails")
    op.drop_table("jobtypes")
    op.drop_table("expenses")
    op.drop_table("customers")
    op.drop_table("agencys")
    # ### end Alembic commands ###
